name: home_automation
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^8.8.1
  shared_preferences: ^0.5.7+3
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
  - images/